project_name: tssh-patched

builds:
  - id: tssh
    main: ./cmd/tssh
    binary: tssh
    dir: ./trzsz-ssh
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm

  - id: tsshd
    main: ./cmd/tsshd
    binary: tsshd
    dir: ./tsshd
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm

archives:
  - id: tssh
    builds:
      - tssh
    name_template: >-
      tssh_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

  - id: tsshd
    builds:
      - tsshd
    name_template: >-
      tsshd_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Version }}.next"

checksum:
  name_template: "tssh-patched_{{ .Version }}_checksums.txt"

release:
  draft: false
  prerelease: auto
  name_template: "{{ .ProjectName }} v{{ .Version }}"
